### ISSUE TITLE
Crash when uploading GIFs and possibly videos too

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#512]
On the last version, several people have reported a crash when it comes to uploading GIFs (verified by @Komposten ) and a few others say the same about uploading videos.

In the case of videos, I have asked them to share their raw, unprocessed media files so we can debug it further.

**Comment by lifenautjoe** [comment]
Debug logs on the GIF Crash provided by @Komposten 

```
02-11 12:26:57.898 10618 10618 I MainActivity: sending intent to flutter
02-11 12:26:57.900 10618 10634 I flutter : Loading flutter-ffmpeg.
02-11 12:26:57.907 10618 10618 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/social.openbook.app-2/base.apk"],nativeLibraryDirectories=[/data/app/social.openbook.app-2/lib/arm64, /data/app/social.openbook.app-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libmobileffmpeg-abidetect.so"
02-11 12:26:57.907 10618 10618 E flutter : 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
02-11 12:26:57.907 10618 10618 E flutter : 	at java.lang.System.loadLibrary(System.java:1530)
02-11 12:26:57.907 10618 10618 E flutter : 	at com.arthenica.mobileffmpeg.AbiDetect.<clinit>()
02-11 12:26:57.907 10618 10618 E flutter : 	at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
02-11 12:26:57.907 10618 10618 E flutter : 	at com.arthenica.mobileffmpeg.Config.<clinit>()
02-11 12:26:57.907 10618 10618 E flutter : 	at com.arthenica.mobileffmpeg.Config.a()
02-11 12:26:57.907 10618 10618 E flutter : 	at c.a.a.a.d.a()
02-11 12:26:57.907 10618 10618 E flutter : 	at e.a.c.a.k$a.a()
02-11 12:26:57.907 10618 10618 E flutter : 	at io.flutter.embedding.engine.b.b.a()
02-11 12:26:57.907 10618 10618 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
02-11 12:26:57.907 10618 10618 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
02-11 12:26:57.907 10618 10618 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:323)
02-11 12:26:57.907 10618 10618 E flutter : 	at android.os.Looper.loop(Looper.java:136)
02-11 12:26:57.907 10618 10618 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:6111)
02-11 12:26:57.907 10618 10618 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
02-11 12:26:57.907 10618 10618 E flutter : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
02-11 12:26:57.907 10618 10618 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
02-11 12:26:57.907 10618 10618 E flutter : 
02-11 12:26:57.908 10618 10618 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
```

**Comment by uiboy** [comment]
Appears it was just a missing library on the build apk, closing this for now.
